### ISSUE TITLE
[FEATURE] Local code quality checks with pre-commit tool/hook

### ISSUE THREAD

**Issue by bramstoeller** [alliander-opensource/power-grid-model#102]
**Use pre-commit to check code quality locally before committing**

The [`pre-commit`](https://pypi.org/project/pre-commit/) tool is a very handy tool to run linters etc before committing the code. It is up to the user to activate the pre-commit hook or not.

I would suggest adding the following `.pre-commit-config.yaml` file:
```yaml
repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
      - id: reuse
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3.8
```

Then we need to add `pre-commit` to the dev requirements and users can choose to activate it by executing:
```bash
pre-commit install
```

I would like to extend the pre-commit file with `isort`, `flake8` and `mypy`, but then we should also add them to the github pipeline

```yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
```
